/**
 * Course: COMP 426
 *
 * This file defines data of profile pages.
 */
/**
 * Represents a list of user profiles (based on instagram friends)
 */
const profileData = [{
    id: marcus,
    age: "22",
    dob: 10-07-1997,
    gender: male,
    zodiac: libra,
    matches: [gemini, sagittarius, aries, aquarius, leo, libra],
    name: "Marcus Vela",
    img: "../../images/marcus.jpeg",
    bio: "I enjoy long walks on the beach and an occasional cool glass of fruit punch.",
    interests: "skiing, cooking, Netflix & Chill",
    insta: "https://instagram.com/marcusvofficial/",
},
{
    id: brennora,
    age: "20",
    dob: 11-03-1999,
    gender: female,
    zodiac: scorpio,
    matches: [taurus, scorpio, cancer, pisces, virgo],
    name: "Brennora Cameron",
    img: "../../images/galaxy.jpeg",
    bio: "I just wanna smoke, eat chicken wings, and listen to R&B",
    interests: "dancing, coding, zumba",
    insta: "https://www.instagram.com/xoxo_brennora/",
},
{
    id: theda,
    age: "16",
    dob: 04-10-2003,
    gender: female,
    zodiac: aries,
    matches: [taurus, gemini, sagittarius, aries, aquarius, leo, cancer, libra],
    name: "Theda Cameron",
    img: "../../images/galaxy.jpeg",
    bio: "Handle me? Who gon handle me?",
    interests: "dancing, cooking, karate",
    insta: "https://www.instagram.com/thedachrisse/",
},
{
    id: chigo,
    age: "23",
    dob: 08-05-1996,
    gender: male,
    zodiac: leo,
    matches: [gemini, sagittarius, aries, aquarius, libra],
    name: "Chigo Montonui",
    img: "../../images/galaxy.jpeg",
    bio: "Find out for yourself...",
    interests: "dancing, video games, eating, shopping",
    insta: "https://www.instagram.com/chigo.m.o/",
},
{
    id: sean,
    age: "22",
    dob: 01-26-1997,
    gender: male,
    zodiac: aquarius,
    matches: [gemini, sagittarius, aries, leo, libra],
    name: "Sean King",
    img: "../../images/galaxy.jpeg",
    bio: "If you a hot girl, I'm a city boy bih :)",
    interests: "Netflix & Chill, swimming, partying",
    insta: "https://www.instagram.com/sean_king4/",
},
{
    id: tre,
    age: "21",
    dob: 12-04-1998,
    gender: male,
    zodiac: sagittarius,
    matches: [gemini, sagittarius, aries, leo, libra, aquarius],
    name: "Tre Shaw",
    img: "../../images/galaxy.jpeg",
    bio: "LackofWorries . UNC DB #25",
    interests: "football, movies, pizza",
    insta: "https://www.instagram.com/_kingdos_/",
},
];
