/**
 * Course: COMP 426
 *
 * This file defines data of profile pages.
 */
/**
 * Represents a list of user profiles (based on instagram friends)
 */
const profileData = [{
    id: marcus,
    age: "22",
    dob: 10-07-1997,
    gender: male,
    like: [female],
    zodiac: libra,
    matches: [gemini, sagittarius, aries, aquarius, leo, libra],
    name: "Marcus Vela",
    img: "../../images/marcus.jpeg",
    bio: "I enjoy long walks on the beach and an occasional cool glass of fruit punch.",
    interests: "skiing, cooking, Netflix & Chill",
    insta: "https://instagram.com/marcusvofficial/",
},
{
    id: brennora,
    age: "20",
    dob: 11-03-1999,
    gender: female,
    like: [male],
    zodiac: scorpio,
    matches: [taurus, scorpio, cancer, pisces, virgo],
    name: "Brennora Cameron",
    img: "../../images/galaxy.jpeg",
    bio: "I just wanna smoke, eat chicken wings, and listen to R&B",
    interests: "dancing, coding, zumba, music",
    insta: "https://www.instagram.com/xoxo_brennora/",
},
{
    id: theda,
    age: "16",
    dob: 04-10-2003,
    gender: female,
    like: [female, male],
    zodiac: aries,
    matches: [taurus, gemini, sagittarius, aries, aquarius, leo, cancer, libra],
    name: "Theda Cameron",
    img: "../../images/galaxy.jpeg",
    bio: "Handle me? Who gon handle me?",
    interests: "dancing, cooking, karate",
    insta: "https://www.instagram.com/thedachrisse/",
},
{
    id: chigo,
    age: "23",
    dob: 08-05-1996,
    gender: male,
    like: [female],
    zodiac: leo,
    matches: [gemini, sagittarius, aries, aquarius, libra],
    name: "Chigo Montonui",
    img: "../../images/galaxy.jpeg",
    bio: "Find out for yourself...",
    interests: "dancing, video games, eating, shopping",
    insta: "https://www.instagram.com/chigo.m.o/",
},
{
    id: sean,
    age: "22",
    dob: 01-26-1997,
    gender: male,
    like: [female],
    zodiac: aquarius,
    matches: [gemini, sagittarius, aries, leo, libra],
    name: "Sean King",
    img: "../../images/galaxy.jpeg",
    bio: "If you a hot girl, I'm a city boy bih :)",
    interests: "Netflix & Chill, swimming, partying",
    insta: "https://www.instagram.com/sean_king4/",
},
{
    id: ralph,
    age: "21",
    dob: 12-04-1998,
    gender: male,
    like: [female],
    zodiac: sagittarius,
    matches: [gemini, sagittarius, aries, leo, libra, aquarius],
    name: "Ralph Bickley",
    img: "../../images/galaxy.jpeg",
    bio: "Spider Xan .. ykwtfgo",
    interests: "trapping, rapping, music",
    insta: "https://www.instagram.com/ralphdaplug/",
},
{
    id: ange,
    age: "20",
    dob: 09-15-1999,
    gender: female,
    like: [male],
    zodiac: virgo,
    matches: [taurus, capricorn, cancer, pisces, scorpio],
    name: "Ange Barasabwa",
    img: "../../images/galaxy.jpeg",
    bio: "fine lil bittie from Rwanda, whatchu know bout that?",
    interests: "dancing, laughing, spicy food",
    insta: "https://www.instagram.com/angepangee/",
},
{
    id: zay,
    age: "22",
    dob: 03-14-1997,
    gender: male,
    like: [female],
    zodiac: pisces,
    matches: [taurus, capricorn, cancer, pisces, scorpio, virgo],
    name: "Zay Marshall",
    img: "../../images/galaxy.jpeg",
    bio: "A king living his best life",
    interests: "modeling, astrology, history",
    insta: "https://www.instagram.com/pharaoh_zayy_/",
},
{
    id: null,
    age: "20",
    dob: 00-00-1990,
    gender: male,
    like: [female, male],
    zodiac: gemini,
    matches: [gemini, sagittarius, aries, aquarius, leo, libra],
    name: "null",
    img: "../../images/galaxy.jpeg",
    bio: "null",
    interests: "null",
    insta: "https://www.instagram.com/null/",
},
{
    id: null,
    age: "20",
    dob: 00-00-1990,
    gender: male,
    like: [female, male],
    zodiac: cancer,
    matches: [taurus, capricorn, cancer, pisces, scorpio, virgo, aries],
    name: "null",
    img: "../../images/galaxy.jpeg",
    bio: "null",
    interests: "null",
    insta: "https://www.instagram.com/null/",
},
{
    id: null,
    age: "20",
    dob: 00-00-1990,
    gender: male,
    like: [female, male],
    zodiac: capricorn,
    matches: [taurus, cancer, pisces, virgo],
    name: "null",
    img: "../../images/galaxy.jpeg",
    bio: "null",
    interests: "null",
    insta: "https://www.instagram.com/null/",
},
{
    id: null,
    age: "20",
    dob: 00-00-1990,
    gender: male,
    like: [female, male],
    zodiac: taurus,
    matches: [taurus, capricorn, scorpio, aries, cancer, pisces, virgo],
    name: "null",
    img: "../../images/galaxy.jpeg",
    bio: "null",
    interests: "null",
    insta: "https://www.instagram.com/null/",
},
];
