/*Represents a list of zodiacs and how compatable they are with other signs (if the compatability is 70% or above)*/
const zodiacs = [{
    id: scorpio,
    taurus: 95,
    capricorn: 60,
    gemini: 1,
    scorpio: 65,
    sagittarius: 25,
    aries: 50,
    aquarius: 40,
    leo: 5,
    cancer: 90,
    virgo: 65,
    libra: 45,
    pisces: 70,
},
{
    id: taurus,
    taurus: 95,
    capricorn: 85,
    gemini: 5,
    scorpio: 95,
    sagittarius: 25,
    aries: 65,
    aquarius: 15,
    leo: 50,
    cancer: 95,
    virgo: 85,
    libra: 35,
    pisces: 99,
},
{
    id: capricorn,
    taurus: 85,
    capricorn: 40,
    gemini: 1,
    scorpio: 60,
    sagittarius: 5,
    aries: 5,
    aquarius: 5,
    leo: 5,
    cancer: 99,
    virgo: 65,
    libra: 15,
    pisces: 99,
},
{
    id: gemini,
    taurus: 5,
    capricorn: 1,
    gemini: 80,
    scorpio: 1,
    sagittarius: 90,
    aries: 90,
    aquarius: 85,
    leo: 90,
    cancer: 5,
    virgo: 5,
    libra: 80,
    pisces: 15,
},
{
    id: sagittarius,
    taurus: 25,
    capricorn: 5,
    gemini: 90,
    scorpio: 25,
    sagittarius: 65,
    aries: 95,
    aquarius: 80,
    leo: 99,
    cancer: 40,
    virgo: 30,
    libra: 90,
    pisces: 30,
},
{
    id: aries,
    taurus: 65,
    capricorn: 5,
    gemini: 90,
    scorpio: 50,
    sagittarius: 95,
    aries: 65,
    aquarius: 65,
    leo: 90,
    cancer: 70,
    virgo: 10,
    libra: 80,
    pisces: 20,
},
{
    id: aquarius,
    taurus: 15,
    capricorn: 5,
    gemini: 85,
    scorpio: 40,
    sagittarius: 80,
    aries: 65,
    aquarius: 50,
    leo: 99,
    cancer: 1,
    virgo: 1,
    libra: 90,
    pisces: 50,
},
{
    id: leo,
    taurus: 50,
    capricorn: 5,
    gemini: 90,
    scorpio: 5,
    sagittarius: 99,
    aries: 90,
    aquarius: 99,
    leo: 50,
    cancer: 30,
    virgo: 5,
    libra: 90,
    pisces: 1,
},
{
    id: cancer,
    taurus: 95,
    capricorn: 99,
    gemini: 5,
    scorpio: 90,
    sagittarius: 40,
    aries: 70,
    aquarius: 1,
    leo: 30,
    cancer: 65,
    virgo: 95,
    libra: 40,
    pisces: 85,
},
{
    id: virgo,
    taurus: 85,
    capricorn: 65,
    gemini: 5,
    scorpio: 65,
    sagittarius: 30,
    aries: 10,
    aquarius: 1,
    leo: 5,
    cancer: 95,
    virgo: 30,
    libra: 1,
    pisces: 99,
},
{
    id: libra,
    taurus: 35,
    capricorn: 15,
    gemini: 80,
    scorpio: 45,
    sagittarius: 90,
    aries: 80,
    aquarius: 90,
    leo: 90,
    cancer: 40,
    virgo: 1,
    libra: 65,
    pisces: 50,
},
{
    id: pisces,
    taurus: 99,
    capricorn: 99,
    gemini: 15,
    scorpio: 70,
    sagittarius: 30,
    aries: 20,
    aquarius: 50,
    leo: 1,
    cancer: 85,
    virgo: 99,
    libra: 50,
    pisces: 75,
},
];